version: "3"
services:

  splash:
    image: "scrapinghub/splash"
    restart: unless-stopped
    expose:
      - "5023"
      - "8050"
      - "8051"

  scraper:
    build: ./scraper
    restart: unless-stopped
    volumes:
      - ./scraper/code:/code
      - images:/images
      - data:/data
    depends_on:
      - splash
    env_file:
      - ./scraper/.env
    command: ["./init.sh"]
    ports:
      - "8081:8080"
    tty: true

volumes:
  images:
  data:
